### ISSUE TITLE
Twitter links are not correct

### ISSUE THREAD

**Issue by yoannfleurydev** [CodeursEnSeine/CodeursEnSeine-app#4]
Links include the `@` so they do not work.

**Comment by arashemadi** [comment]
Hello @yoannfleurydev. May I work on this, please?

**Comment by yoannfleurydev** [comment]
Hello @arashemadi , sure 👍

**Comment by yoannfleurydev** [comment]
I'm so sorry, I didn't check before but there is already a PR (#5) for this issue. Maybe next time 😅
